### ISSUE TITLE
Fullscreen terminal has transparent background

### ISSUE THREAD

**Issue by dylanjt** [JacobCoffee/blackula#1]
When in fullscreen mode, the Zed terminal switches to a transparent background, making it difficult to read terminal text:

<img width="266" alt="Screenshot 2024-04-19 at 9 58 03 PM" src="https://github.com/JacobCoffee/blackula/assets/7364545/e0f6ab95-b129-40d4-a3a6-37e356f68422">

Aside, I've been checking for a black Dracula theme since I started using Zed. Thank you!!

**Comment by JacobCoffee** [comment]
Thanks for the issue! I updated it, not 100% sure here but I think the next extensions update will have this as `v0.1.1`.

**Comment by dylanjt** [comment]
@JacobCoffee Been waiting for this to land in Zed. I looked around just now, and also not 100% sure but I think maybe you need to open a PR with this update to zed-industries/extensions? _A la_ #67 on that repo.

**Comment by JacobCoffee** [comment]
Ahh yeah.. sorry about that ☹️ I don't know why i expected it to just be magic 😅 
https://github.com/zed-industries/extensions/pull/620

**Comment by JacobCoffee** [comment]
Hey @dylanjt  - should be available now
<img width="282" alt="image" src="https://github.com/JacobCoffee/blackula/assets/45884264/2fe29b6d-e6a4-4f3c-9f94-f535aba382aa">
